# stack 串聯(條件: 合併時表格行列要相容)
## vstack(垂直) / hstack (水平)

In [27]:
a1 = np.arange(95,100)
a1

array([95, 96, 97, 98, 99])

In [28]:
a2 = np.arange(1,11).reshape(2,5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
#vstack 垂直合併
s1 = np.vstack((a1,a2))
s1

array([[95, 96, 97, 98, 99],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
np.vstack(
    (
        np.arange(5),
        np.linspace(0,1,5),
        np.eye(5)
    )
)

array([[0.  , 1.  , 2.  , 3.  , 4.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  ]])

In [44]:
#hstack水平合併
a3 = np.arange(90,96).reshape(2,3)
a3

array([[90, 91, 92],
       [93, 94, 95]])

In [45]:
a4 = np.arange(1,11).reshape(2,5)
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
s2 = np.hstack((a3,a4))
s2

array([[90, 91, 92,  1,  2,  3,  4,  5],
       [93, 94, 95,  6,  7,  8,  9, 10]])