In [26]:
import numpy as np

x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#index 取值
x[-2]

array([0, 1, 2, 3, 4])

In [13]:
x.shape = (2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
#上方變成(2,5)的格式,取index=[1,3]
# x[1,3]      #8  

x[1,-1]

9

In [86]:
#將數值倒著:10~1
x = np.arange(10,0,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [89]:
a = np.arange(0,11,2)  #start,end,間距
a

array([ 0,  2,  4,  6,  8, 10])

# 練習一:

In [42]:
import numpy as np
a1 = np.array([1,2,3,4] ,dtype = np.int16) #可設定dtype
a1

array([1, 2, 3, 4], dtype=int16)

In [43]:
#dtype = uint8 (表示 0~255)
#若數值超出255,則會從頭0算起

a2= np.array([1,2,3,300], dtype = np.uint8)
a2

array([ 1,  2,  3, 44], dtype=uint8)

In [44]:
#dtype = int8 (表示 -128~127)
#若數值超出127,則會從頭-128算起

a3= np.array([1,2,3,128], dtype = np.int8)
a3

array([   1,    2,    3, -128], dtype=int8)

In [46]:
#dtype=int64 整數型態
#若有小數點, 則直接無條件捨去

a4 = np.array([1,2,3,9.9,9.1], dtype = np.int64)
a4

array([1, 2, 3, 9, 9], dtype=int64)

# 練習二:

In [54]:
import numpy as np

m_py = [
    [1,0,0],
    [0,1,0],
    [0,0,1]    
]

m2 =np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
) 

In [55]:
m_py

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [56]:
m1 = np.array(m_py, dtype = np.int16)
m1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [59]:
#m_py = (3,3)
#rows =3

len(m1)  

3

In [68]:
#m1 = (3,3)
#3*3

m1.size

9

In [69]:
#shape

m1.shape

(3, 3)

In [65]:
#m2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
#m2 = (4,3)
#rows =4

len(m2)

4

In [67]:
#m2 = (4,3)
#4*3

m2.size

12

### np.zeros / np.ones / np.full / np.eye /np.arrange / np.linspace / np.random.random

In [73]:
#np.zeros
np.zeros(3)

array([0., 0., 0.])

In [74]:
np.zeros ((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
#去除小數點

a = np.zeros(5,dtype = int)
a

array([0, 0, 0, 0, 0])

In [90]:
a = np.zeros( (4,3), dtype=np.uint8)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [91]:
m = np.ones(5)
m

array([1., 1., 1., 1., 1.])

In [83]:
#one
m = np.ones((10,2), dtype= np.float64)
m

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [84]:
#full
#將3.888 代入shape(2,5)

m = np.full((2,5), 3.888, dtype=np.float32)  
m

array([[3.888, 3.888, 3.888, 3.888, 3.888],
       [3.888, 3.888, 3.888, 3.888, 3.888]], dtype=float32)

In [3]:
#eye
#會形成一個對角

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
np.eye(5,3, dtype=np.uint16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint16)

In [5]:
np.linspace(0,5,10)  #包含5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# 練習三:

In [13]:
import math

x_code = np.linspace(-2*math.pi, 2*math.pi,50)
x_code

array([-6.28318531, -6.02672876, -5.77027222, -5.51381568, -5.25735913,
       -5.00090259, -4.74444605, -4.48798951, -4.23153296, -3.97507642,
       -3.71861988, -3.46216333, -3.20570679, -2.94925025, -2.6927937 ,
       -2.43633716, -2.17988062, -1.92342407, -1.66696753, -1.41051099,
       -1.15405444, -0.8975979 , -0.64114136, -0.38468481, -0.12822827,
        0.12822827,  0.38468481,  0.64114136,  0.8975979 ,  1.15405444,
        1.41051099,  1.66696753,  1.92342407,  2.17988062,  2.43633716,
        2.6927937 ,  2.94925025,  3.20570679,  3.46216333,  3.71861988,
        3.97507642,  4.23153296,  4.48798951,  4.74444605,  5.00090259,
        5.25735913,  5.51381568,  5.77027222,  6.02672876,  6.28318531])

In [14]:
y = np.array([math.sin(x) for x in x_code])
y

array([ 2.44929360e-16,  2.53654584e-01,  4.90717552e-01,  6.95682551e-01,
        8.55142763e-01,  9.58667853e-01,  9.99486216e-01,  9.74927912e-01,
        8.86599306e-01,  7.40277997e-01,  5.45534901e-01,  3.15108218e-01,
        6.40702200e-02, -1.91158629e-01, -4.33883739e-01, -6.48228395e-01,
       -8.20172255e-01, -9.38468422e-01, -9.95379113e-01, -9.87181783e-01,
       -9.14412623e-01, -7.81831482e-01, -5.98110530e-01, -3.75267005e-01,
       -1.27877162e-01,  1.27877162e-01,  3.75267005e-01,  5.98110530e-01,
        7.81831482e-01,  9.14412623e-01,  9.87181783e-01,  9.95379113e-01,
        9.38468422e-01,  8.20172255e-01,  6.48228395e-01,  4.33883739e-01,
        1.91158629e-01, -6.40702200e-02, -3.15108218e-01, -5.45534901e-01,
       -7.40277997e-01, -8.86599306e-01, -9.74927912e-01, -9.99486216e-01,
       -9.58667853e-01, -8.55142763e-01, -6.95682551e-01, -4.90717552e-01,
       -2.53654584e-01, -2.44929360e-16])

In [15]:
#random.random()每次生成的数都是随机的。使用 random.seed(x) ,x 可以是任意数字，下次生成的随机数将会是同一个。
np.random.seed(0)  
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [28]:
from numpy import random as npr

npr.seed(0)
npr.randint(1,7,(5,10))  #隨機1~6, (5,10矩陣)

array([[5, 6, 1, 4, 4, 4, 2, 4, 6, 3],
       [5, 1, 1, 5, 3, 2, 1, 2, 6, 2],
       [6, 1, 2, 5, 4, 1, 4, 6, 1, 3],
       [4, 1, 2, 4, 6, 4, 4, 1, 2, 2],
       [2, 1, 3, 5, 4, 4, 3, 5, 3, 1]])

In [36]:
#reshape
import numpy as np
arr = np.arange(10)
m1 = arr.reshape(2,5)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
arr.shape

(10,)

In [38]:
m1[1][3]

8

# 練習

In [42]:
arr = np.random.randint(0,50,6)
arr

array([15,  4, 41, 42, 31,  1])

In [43]:
arr.max()

42

In [44]:
arr.min()

1

In [45]:
arr.argmax() #查詢最大值在第幾位

3

In [47]:
arr.argmin() #查詢最小值在第幾位

5

In [50]:
m2 = arr.reshape(3,2)
m2

array([[15,  4],
       [41, 42],
       [31,  1]])